name: Java CI with Maven and Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

    # Add your deployment step here
    - name: Deploy to staging
      uses: easingthemes/ssh-deploy@v2
      with:
        server_ip: ${{ secrets.STAGING_SERVER_IP }}
        server_username: ${{ secrets.STAGING_SERVER_USERNAME }}
        server_port: ${{ secrets.STAGING_SERVER_PORT }}
        ssh_private_key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
        local_path: 'target/JoinJoy-0.0.1-SNAPSHOT.jar'
        remote_path: '/path/to/your/application'
